### ISSUE TITLE
Issue in CreateKeyPair Test

### ISSUE THREAD

**Issue by praveenkmurthy** [google/pkcs11test#1]
File:  keypair.cc
Test: TEST_F(ReadWriteSessionTest, CreateKeyPairObjects)

While populating the data for private key template, improper use of stack variables.

if (!keydata.prime1.empty()) {
    string data = hex_decode(keydata.prime1);
    private_attrs.push_back({CKA_PRIME_1, (CK_BYTE_PTR)data.data(), prime1.size()});
  }

--  data variable goes out of scope once we exit if condition

This is applicable for other attributes as well - prime2, exponent1, exponent2, coefficient

Regards,
Praveen

**Comment by daviddrysdale** [comment]
Well spotted, many thanks.
