### ISSUE TITLE
ReadOnlySessionTest.SeedRandom should allow CKR_RANDOM_SEED_NOT_SUPPORTED

### ISSUE THREAD

**Issue by jasonbking** [google/pkcs11test#11]
Currently, if an RNG is present, the ReadOnlySessionTest.SeedRandom test is preformed where the RNG is seeded with a constant known value.  I cannot find any text in the current PKCS#11 spec that requires an RNG to support explicit seeding.  That would imply the test should not fail when CKR_RANDOM_SEED_NOT_SUPPORTED is returned.

**Comment by daviddrysdale** [comment]
Seems reasonable.  Does #12 work for you?

**Comment by jasonbking** [comment]
Looks good to me
