### ISSUE TITLE
Allow a range of acceptable return values for some tests?

### ISSUE THREAD

**Issue by inorton** [google/pkcs11test#14]
There are a number of tests that fail against the library I'm testing with slightly different return values.  For instance,   

`EncryptDecryptInitInvalid/5` expects `CKR_KEYTYPE_INCONSISTENT`

The test calls `C_DecryptInit` with a RSA mech and a symmetric key.   

In this particular case you could equally say the mech is wrong (`CKR_MECHANISM_INVALID`) or the key is of the wrong type (`CKR_KEYTYPE_INCONSISTENT`).

The standard doesn't seem to mandate either as preferred.

What do you think?

**Comment by inorton** [comment]
Actually, I think I've answered this query by reading http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html

> CKR_KEY_TYPE_INCONSISTENT: The specified key is not the correct type of key to use with the specified mechanism.

So key type must match the mechanism rather than mechanism must match key type

**Comment by daviddrysdale** [comment]
Yeah, on a quick read I'd take the spec as implying that `CKR_KEYTYPE_INCONSISTENT` should be returned here, as the mechanism isn't actually invalid (assuming that the token does actually support RSA).

**Comment by daviddrysdale** [comment]
(In general though I'm happy to take PRs that adjust tests to accept a wider range of error codes, if it's vaguely plausible spec-wise&hellip;)
