### ISSUE TITLE
pointer passed into pReserved of CK_C_INITIALIZE_ARGS  passed to C_Initialize 

### ISSUE THREAD

**Issue by inorton** [google/pkcs11test#2]
Hi there,

I've just ran your test suite and have found it passes a value in the reserved member of the C_Initialize args.

The library I'm testing with makes use of this reserved pointer if set for internal testing data (perhaps it shouldn't) and the test makes the library segfault.

What is the expected behaviour for a well formed library? Can I easily turn this off?

**Comment by daviddrysdale** [comment]
Is this specifically just the `Init.InitArgsBadReserved` test?

That test is checking that the PKCS#11 library complies with the text in [section 11.4 of the spec](https://www.cryptsoft.com/pkcs11doc/v220/group__SEC__11__4__GENERAL__PURPOSE__FUNCTIONS.html), which says:

"For this version of Cryptoki, the value of `pReserved` thereby obtained must be `NULL_PTR`; if it's not, then `C_Initialize` should return with the value `CKR_ARGUMENTS_BAD`."

As a quick workaround, you should be able to skip that particular test by using a command-line argument like `--gtest_filter=-Init.InitArgsBadReserved` (or you could just disable that test locally by changing its name to `DISABLED_InitArgsBadReserved`).

**Comment by inorton** [comment]
Many thanks!
