### ISSUE TITLE
C_SeedRandom should use INVALID_SESSION_HANDLE not INVALID_SLOT_ID

### ISSUE THREAD

**Issue by Hlipa** [google/pkcs11test#24]
See for example here:

https://github.com/google/pkcs11test/blob/a9cd0cb14db6afe0048b04daf64f577e56626dbc/rng.cc#L41

first arg in C_SeedRandom is session handle not slot ID.

**Comment by daviddrysdale** [comment]
So it does, well spotted.  Does #25 look better?
