### ISSUE TITLE
Camellia and SHA224 mechanisms do not have flags mapping

### ISSUE THREAD

**Issue by Hlipa** [google/pkcs11test#26]
PKCS11Test.EnumerateSlots fails for Camellia and SHA224 mechanism types because they don't have flags mapping in global.cc:

mechanism[13]=CKM_SHA224_RSA_PKCS CK_MECHANISM_INFO {.ulMinKeySize=256, .ulMaxKeySize=8192, .flags=CKF_SIGN|CKF_VERIFY}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 10240
Expected: 0
mechanism[45]=CKM_SHA224 CK_MECHANISM_INFO {.ulMinKeySize=0, .ulMaxKeySize=0, .flags=CKF_DIGEST}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 1024
Expected: 0
mechanism[46]=CKM_SHA224_HMAC CK_MECHANISM_INFO {.ulMinKeySize=1, .ulMaxKeySize=64, .flags=CKF_SIGN|CKF_VERIFY}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 10240
Expected: 0
mechanism[47]=CKM_SHA224_HMAC_GENERAL CK_MECHANISM_INFO {.ulMinKeySize=1, .ulMaxKeySize=64, .flags=CKF_SIGN|CKF_VERIFY}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 10240
Expected: 0
mechanism[64]=CKM_SHA224_KEY_DERIVATION CK_MECHANISM_INFO {.ulMinKeySize=1, .ulMaxKeySize=28, .flags=CKF_DERIVE}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 524288
Expected: 0
mechanism[73]=CKM_CAMELLIA_KEY_GEN CK_MECHANISM_INFO {.ulMinKeySize=16, .ulMaxKeySize=32, .flags=CKF_GENERATE}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 32768
Expected: 0
mechanism[74]=CKM_CAMELLIA_ECB CK_MECHANISM_INFO {.ulMinKeySize=16, .ulMaxKeySize=32, .flags=CKF_ENCRYPT|CKF_DECRYPT|CKF_WRAP|CKF_UNWRAP}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 393984
Expected: 0
mechanism[75]=CKM_CAMELLIA_CBC CK_MECHANISM_INFO {.ulMinKeySize=16, .ulMaxKeySize=32, .flags=CKF_ENCRYPT|CKF_DECRYPT|CKF_WRAP|CKF_UNWRAP}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 393984
Expected: 0
mechanism[76]=CKM_CAMELLIA_CBC_PAD CK_MECHANISM_INFO {.ulMinKeySize=16, .ulMaxKeySize=32, .flags=CKF_ENCRYPT|CKF_DECRYPT|CKF_WRAP|CKF_UNWRAP}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 393984
Expected: 0
mechanism[77]=CKM_CAMELLIA_CTR CK_MECHANISM_INFO {.ulMinKeySize=16, .ulMaxKeySize=32, .flags=CKF_ENCRYPT|CKF_DECRYPT|CKF_WRAP|CKF_UNWRAP}
slot.cc:151: Failure
Value of: extra_flags
  Actual: 393984
Expected: 0

**Comment by daviddrysdale** [comment]
Thanks, that's probably missing because I originally worked from base v2.20 without amendment 3.  

Do you want to send a PR to add support (assuming the [CLA](https://cla.developers.google.com/) is OK)?
