### ISSUE TITLE
Clarification related to InitToken Tests

### ISSUE THREAD

**Issue by praveenkmurthy** [google/pkcs11test#3]
In slot.cc, TEST_F(PKCS11Test, TokenInit),

After C_InitToken() call with g_so_pin , there is a comment which says "both the pins would have been reset. we need to set them back". But as per PKCS#11 v2.40 doc, it says the value of SO Pin at the end of C_InitToken() call shall be that of pPin which is passed as an argument to the call. In our case it will be g_so_pin and NOT g_reset_so_pin.

**Comment by daviddrysdale** [comment]
Good spot, thanks.

(Aside: I mostly wrote this for working with [Chaps](https://github.com/google/chaps-linux), which has its own [way](https://github.com/google/chaps-linux#pkcs11-slots-and-users) of dealing with users and so doesn't support [InitToken/SO login](https://chromium.googlesource.com/chromiumos/platform2/+/master/chaps/chaps_service.cc#217).)
