### ISSUE TITLE
Key Wrap Invalid Test not true

### ISSUE THREAD

**Issue by civanahmetyasin** [google/pkcs11test#34]
1-
https://github.com/google/pkcs11test/blob/bfc5bc1f270078bc35b7a827b00e967ffb028095/key.cc#L172
İf this test returning CKR_OK 

why doesn't this key have AES, RSA, DES3
https://github.com/google/pkcs11test/blob/bfc5bc1f270078bc35b7a827b00e967ffb028095/key.cc#L154

and has a mechanism not supported in this code
https://github.com/google/pkcs11test/blob/bfc5bc1f270078bc35b7a827b00e967ffb028095/key.cc#L107
Why you do not use _CKM_DES3_ECB_ or _CKM_AES_KEY_WRAP_ ?

Because ONE DES not supported, I'm getting an error here.
For example, you must see softHSM _C_WrapKey_ function
https://github.com/opendnssec/SoftHSMv2/blob/8f5e4e488fa4c19d56866e27a046680bfc1793d5/src/lib/SoftHSM.cpp#L6302

---
2-
Im have a eror because this **k1_attrs** dont have _CKA_EXTRACTABLE_
https://github.com/google/pkcs11test/blob/bfc5bc1f270078bc35b7a827b00e967ffb028095/key.cc#L101
For example, I might get an error when I test in softHSM.
https://github.com/opendnssec/SoftHSMv2/blob/8f5e4e488fa4c19d56866e27a046680bfc1793d5/src/lib/SoftHSM.cpp#L6415

**Comment by daviddrysdale** [comment]
1) Yeah, assuming the existence of `CKM_DES_ECB` is probably a bit limiting nowadays. At this point the easiest way to fix might be to move the default [keygen](https://github.com/google/pkcs11test/blob/dev/pkcs11test.h#L241) & [wrapping](https://github.com/google/pkcs11test/blob/dev/key.cc#L107) mechanisms to be global variables rather than constants, and add command-line arguments to allow them to be overridden. 

2) On a quick glance SoftHSM seems to be assuming that an absent `CKA_EXTRACTABLE` attribute is the same as `CKA_EXTRACTABLE=false`, which I *think* is a bit strict &ndash; I couldn't immediately find a spec reference to say one way or the other.

**Comment by civanahmetyasin** [comment]
Thank you for your return. Should I make both changes? Should I open the pull request later?

**Comment by civanahmetyasin** [comment]
You must read PKCS11 Cryptographic Token Interface Base Specification [4.2 Common attributes, note 9 ](https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/os/pkcs11-base-v3.0-os.html#_Toc29976553) and [4.10 Secret key objects](https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/os/pkcs11-base-v3.0-os.html#_Toc29976583) for `CKA_EXTRACTABLE` attribute.

**Comment by daviddrysdale** [comment]
> Thank you for your return. Should I make both changes? Should I open the pull request later?

If you could do a pull request that would be great &ndash; thanks!  (If you can, it would be nice to separate the changes as two separate PRs though)

> PKCS11 Cryptographic Token Interface Base Specification ... for CKA_EXTRACTABLE attribute.

Yeah, I know those spec references.  The question is what the spec says about the `CKA_EXTRACTABLE` attribute being **absent** &ndash; does that count as `true`, `false` or neither?  

However, in the meanwhile it seems OK to make the tests cope with a 'stricter' PKCS#11 implementation by explicitly marking keys-to-be-wrapped as `CKA_EXTRACTABLE=true`.

**Comment by fatih-asici** [comment]
> > PKCS11 Cryptographic Token Interface Base Specification ... for CKA_EXTRACTABLE attribute.
> 
> Yeah, I know those spec references. The question is what the spec says about the `CKA_EXTRACTABLE` attribute being **absent** – does that count as `true`, `false` or neither?

The associated footnote with `CKA_EXTRACTABLE` says:

> 9 Default value is token-specific, and may depend on the values of other attributes.

I think the "Default value" should be used if the user does not provide the attribute when generating the object.

**Comment by daviddrysdale** [comment]
Fixed by #35 and #36 &ndash; thanks!
