### ISSUE TITLE
ReadOnlySessionTest.WrapUnwrap - Expected wrong return value

### ISSUE THREAD

**Issue by metekesler** [google/pkcs11test#44]
"ReadOnlySessionTest.WrapUnwrap" In this test case, it is requested to create a Private Key during R / W Public operation. It is written that this operation should not be allowed in the section "2.6.4 Permitted object accesses by sessions". Therefore, the transaction cannot be expected to be successful here. The return value of the function should be "CKR_USER_NOT_LOGGED_IN" but the expected value is "CKR_OK". Could there be a bug in this testing process?

[2.6.4 Permitted object accesses by sessions](http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html#_Toc406759993)

OUTPUT:
```
key.cc:145: Failure
Value of: CK_RV_((g_fns->C_UnwrapKey(session_, &wrap_mechanism, k2.handle(), data, data_len, k3_attrs, 5, &k3)))
  Actual: CKR_USER_NOT_LOGGED_IN
Expected: CK_RV_(0x00000000)
Which is: CKR_OK
```

**Comment by daviddrysdale** [comment]
Would moving these tests to use the `ROUserSessionTest` fixture instead of `ReadOnlySessionTest` fix things?

**Comment by metekesler** [comment]
yes i think this change will fix it

**Comment by metekesler** [comment]
> Would moving these tests to use the `ROUserSessionTest` fixture instead of `ReadOnlySessionTest` fix things?

Hi @daviddrysdale,
any progress on this?

**Comment by daviddrysdale** [comment]
Does #51 cover it?

**Comment by metekesler** [comment]
> Does #51 cover it?

Yes, it does.
