### ISSUE TITLE
ReadWriteSessionTest.TookanAttackA1 - update CKM_DES_ECB as CKM_DES3_ECB

### ISSUE THREAD

**Issue by metekesler** [google/pkcs11test#46]
TookanAttackA1 also failed the test because the mechanism type "CKM_DES_ECB" is old version. It may be more accurate to update this type to CKM_DES3_ECB.

 - CK_MECHANISM wrap_mechanism = {CKM_DES_ECB, NULL_PTR, 0};
 + CK_MECHANISM wrap_mechanism = {CKM_DES3_ECB, NULL_PTR, 0};

**Comment by daviddrysdale** [comment]
I guess that could use the command-line-specified wrapping mechanism from #35 -- see #47.
