### ISSUE TITLE
Wrong value set in keypair.cc

### ISSUE THREAD

**Issue by metekesler** [google/pkcs11test#48]
Wrong value set for recoveryed_plaintext_len in keypair.cc (line:120)

CK_BYTE recovered_plaintext[1024];
-CK_ULONG recovered_plaintext_len = sizeof(plaintext);
rv = g_fns->C_Decrypt(session_, ciphertext, ciphertext_len, recovered_plaintext, &recovered_plaintext_len);

+CK_ULONG recovered_plaintext_len = sizeof(recovered_plaintext);

**Comment by daviddrysdale** [comment]
Could you send this as a pull request? Thanks.

**Comment by metekesler** [comment]
#49
I create a pull request for  this issue. Please review and merge this

**Comment by daviddrysdale** [comment]
Thanks!
