### ISSUE TITLE
WrapUnwrap - Wrong key type set used

### ISSUE THREAD

**Issue by metekesler** [google/pkcs11test#56]
Incorrect key type assigned in test. DES3 object was created but wrong type was given in UnwrapKey operation.

key.cc - Line : 137
-CK_KEY_TYPE key_type = CKK_DES;
+CK_KEY_TYPE key_type = CKK_DES3;

**Comment by daviddrysdale** [comment]
Yeah, looks like that was missed in #35 &ndash; could you send a PR please?
