### ISSUE TITLE
WrapUnwrap - attribute set is missing

### ISSUE THREAD

**Issue by metekesler** [google/pkcs11test#57]
key.cc - Line:138
CKA_EXTRACTABLE must be explicitly specified as true for the new object.

```
CK_ATTRIBUTE k3_attrs[] = {
    {CKA_LABEL, (CK_VOID_PTR)g_label, g_label_len},
    {CKA_CLASS, &key_class, sizeof(key_class)},
    {CKA_KEY_TYPE, (CK_VOID_PTR)&key_type, sizeof(key_type)},
    {CKA_ENCRYPT, (CK_VOID_PTR)&g_ck_true, sizeof(CK_BBOOL)},
    {CKA_DECRYPT, (CK_VOID_PTR)&g_ck_true, sizeof(CK_BBOOL)},
+  {CKA_EXTRACTABLE, (CK_VOID_PTR)&g_ck_true, sizeof(CK_BBOOL)},
    };
```

**Comment by daviddrysdale** [comment]
Hmm, confusing &ndash; the PKCS#11 spec includes example code for `C_UnwrapKey()` that does not include `CKA_EXTRACTABLE` in the template (p.181 of PKCS#11 v2.2, section 5.13 of v2.40) &hellip; but both also include text that "The CKA_EXTRACTABLE attribute is by default set to CK_TRUE. "

Nevertheless, probably worth changing as you describe &ndash; could you send a PR please?
