### ISSUE TITLE
wrong pin set for session - TokenInit

### ISSUE THREAD

**Issue by metekesler** [google/pkcs11test#60]
An attempt is made to log in with g_reset_user_pin at line 347 in slot.cc, but the C_Login error is CKR_PIN_INCORRECT because the password is incorrect. This is actually something that should happen. I think EXPECT_CKR(CKR_PIN_INCORRECT, ...) should be expected here, not EXPECT_CKR_OK or the line "g_reset_user_pin = optarg" should be added under line 181in pkcs11test.cc.

**Comment by daviddrysdale** [comment]
Yeah, the `g_reset_*_pin` values should be overridable from the command line.  Does #61 cover what you need?

**Comment by metekesler** [comment]
> Yeah, the `g_reset_*_pin` values should be overridable from the command line. Does #61 cover what you need?

yes, #61 meets the need.

**Comment by metekesler** [comment]
> > Yeah, the `g_reset_*_pin` values should be overridable from the command line. Does #61 cover what you need?
> 
> yes, #61 meets the need.

You should not forget to add U and O parameters to pkcs11test.cc line:160.

**Comment by daviddrysdale** [comment]
> You should not forget to add U and O parameters to pkcs11test.cc line:160.

Well spotted, thanks.
