### ISSUE TITLE
VENDOR_DEFINED values are not processed correctly

### ISSUE THREAD

**Issue by Hlipa** [google/pkcs11test#64]
All vendor defined values like CKM_VENDOR_DEFINED are minimal not exact value. Standard says:

> [Mechanism types CKM_VENDOR_DEFINED and above are permanently reserved for token vendors.]

but in `mechanism_type_name()` we can see:

`    case CKR_VENDOR_DEFINED: return "CKR_VENDOR_DEFINED";`

instead of:

`    if (val >= CKM_VENDOR_DEFINED) return "CKM_VENDOR_DEFINED";`

It finally leads to situation when function returns "UNKNOWN" instead of "CKM_VENDOR_DEFINED" string.

**Comment by daviddrysdale** [comment]
Well spotted &ndash; could you send a PR?

**Comment by Hlipa** [comment]
yes, will do.

**Comment by bharsaklemukesh975** [comment]
Hi, if it is still open. can I work on this as my first contribution to open source?

**Comment by daviddrysdale** [comment]
Sure, sounds good to me &ndash; thanks.

**Comment by daviddrysdale** [comment]
Fixed by #71
