### ISSUE TITLE
Test EnumerateMechanisms Fails on EC flags

### ISSUE THREAD

**Issue by bryan-hunt** [google/pkcs11test#7]
Based on my reading on the EC mechanisms there are a number of additional flags for the mechanism that need to be provided:
https://www.oasis-open.org/committees/download.php/50389/CKM_ECDSA_FIPS_186_4_v03.pdf

```
An EC key in Cryptoki contains information about which variety of EC it is suited for. It is
preferable that a Cryptoki library, which can perform EC mechanisms, be capable of performing
operations with the two varieties of EC, however this is not required. The
CK_MECHANISM_INFO structure CKF_EC_F_P flag identifies a Cryptoki library
supporting EC keys over Fp whereas the CKF_EC_F_2M flag identifies a Cryptoki library
supporting EC keys over F2m. A Cryptoki library that can perform EC mechanisms must set
either or both of these flags for each EC mechanism.

In these specifications there are also three representation methods to define the domain
parameters for an EC key. Only the ecParameters and the namedCurve choices are supported
in Cryptoki. The CK_MECHANISM_INFO structure CKF_EC_ECPARAMETERS flag
identifies a Cryptoki library supporting the ecParameters choice whereas the
CKF_EC_NAMEDCURVE flag identifies a Cryptoki library supporting the namedCurve
choice. A Cryptoki library that can perform EC mechanisms must set either or both of these flags
for each EC mechanism.

In these specifications, an EC public key (i.e. EC point Q) or the base point G when the
ecParameters choice is used can be represented as an octet string of the uncompressed form or
the compressed form. The CK_MECHANISM_INFO structure CKF_EC_UNCOMPRESS
flag identifies a Cryptoki library supporting the uncompressed form whereas the
CKF_EC_COMPRESS flag identifies a Cryptoki library supporting the compressed form. A
Cryptoki library that can perform EC mechanisms must set either or both of these flags for each
EC mechanism
```

Would it be fair to say that for EC mechanisms (CKM_EC_KEY_PAIR_GEN, CKM_ECDSA, CKM_ECDSA_SHA256, CKM_ECDH1_DERIVE, etc) we should expect to see at least one flag from each of the 3 categories listed above and thus the EnumerateMechanisms needs to differentiate between mechanisms that may support elliptic curves?

**Comment by daviddrysdale** [comment]
Yeah, I think those possible flag values are missing from the allowed values in `EnumerateMechanisms` for EC mechanisms.  (The [pkcs11t.h header file](https://www.oasis-open.org/committees/document.php?document_id=55657) does slightly confusingly say that these flag values are "not available in mechanism information" but the spec text in 12.3 is pretty clear, so that's probably just an unfortunate wording.)

Do you have an EC-capable PKCS#11 implementation to test a change against?

**Comment by bryan-hunt** [comment]
I am developing one yes and recently started using pkcs11test as a compliance test suite to supplement my unit tests. Incorporating the above changes resolves the issue I had encountered based on our common reading of the specification.

I have a number of other EC related items I'll put together in a pull request but this is the only item where there seemed to be a specification concern..

**Comment by daviddrysdale** [comment]
That makes sense - thanks for the update.

BTW, does pull #8 work for your scenario/implementation?

**Comment by bryan-hunt** [comment]
Yes, I pulled the forked ec-flags branch into my project earlier to confirm. Thanks!
