### ISSUE TITLE
How to compile and test via CryptokiMPX in Windows

### ISSUE THREAD

**Issue by hajikhorasani** [google/pkcs11test#9]
I couldn't compile the code on Windows to test a PKCS #11 middle-ware of a token, which loaded by CryptokiMPX.
https://github.com/hajikhorasani/cryptokimpx

**Comment by daviddrysdale** [comment]
I don't have easy access to a Windows environment -- could you provide more details of the build process and the errors?

**Comment by hajikhorasani** [comment]
As I couldn't find any CMake file or MS Visual Studio project, I tried to compile the source code with MinGW, and it was not successful.

**Comment by daviddrysdale** [comment]
Can't really begin to help without some invocation and error details, I'm afraid.
